### ISSUE TITLE
Refactoring current code

### ISSUE THREAD

**Issue by eranik** [eranik/nexpress#3]
Following tasks needs to be done:

1. Rename m.go to main.go
2. "web" directory name is not proper. Rename it to "html-templates"
3. Make golang code object oriented by creating a struct.
4. Read user names and passwords from an external config file.

**Comment by Amd64R** [comment]
1. m.go renamed to main.go
2. "web" directory renamed to "html-templates"
4. MySQL password and hashing added
3. code refactoring is on the way ...
